name: Build Android APK Bundle
on:
  push:
    branches:
      - master
jobs:
  Build-for-android:
    runs-on: ubuntu-latest
    name: Build Android APK Bundle
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: "21" # The JDK version to make available on the path.
      - uses: android-actions/setup-android@v3
      - name: Install deps
        run: npm ci
      - name: Prebuild android native files
        run: npx expo prebuild -p android
      - name: Build android APK Bundle
        run: cd android && ./gradlew assembleRelease
