name: Build Android APK Bundle
on:
  push:
    tags:
      - '*'
jobs:
  Build-for-android:
    name: Build Android APK Bundle
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: "21" # The JDK version to make available on the path.
      - uses: android-actions/setup-android@v3
      - name: Install deps
        run: npm ci
      - name: Prebuild android native files
        run: npx expo prebuild -p android
      - name: Build android APK Bundle
        run: cd android && ./gradlew assembleRelease
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
          overwrite_files: false